### ISSUE TITLE
Milabench v2 on AMD

### ISSUE THREAD

**Issue by Delaunay** [mila-iqia/milabench#21]
# First Issue
```
> milabench install config/standard.yaml  --use-current-env
decompressing input tarball: coco128.tar.gz...OK
decompressing input tarball: tacotron2-minimal.tar.gz...OK
decompressing input tarball: coco2017-minimal.tar.gz...OK
running setup for /data/delaunap/milabench/runs/code/torchbench/torchbenchmark/models/BERT_pytorch...OK
Traceback (most recent call last):
  File "/data/delaunap/conda/envs/rocm/bin/milabench", line 8, in <module>
    sys.exit(main())
  File "/data/delaunap/milabench/milabench/cli.py", line 23, in main
    run_cli(Main)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/coleo/cli.py", line 628, in run_cli
    return call(opts=opts, args=args)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/coleo/cli.py", line 587, in thunk
    result = fn(*args)
  File "/data/delaunap/milabench/milabench/cli.py", line 223, in install
    mp.do_install(dash=simple_dash, force=force, sync=sync)
  File "/data/delaunap/milabench/milabench/multi.py", line 88, in do_install
    pack.checked_install(force=force, sync=sync)
  File "/data/delaunap/milabench/milabench/pack.py", line 98, in checked_install
    self.install_milabench()
  File "/data/delaunap/milabench/milabench/pack.py", line 139, in install_milabench
    self.pip_install("pip", "-U")
  File "/data/delaunap/milabench/milabench/pack.py", line 161, in pip_install
    if self.constraints:
AttributeError: 'TorchBenchmarkPack' object has no attribute 'constraints'
```

Small fix was to add `hasattr(self, "constraints")`

# Second Issue
```
> milabench prepare config/standard.yaml --use-current-env

Traceback (most recent call last):
  File "/data/delaunap/milabench/runs/code/lightning/prepare.py", line 6, in <module>
    from utils import VISION_DATAMODULES, DataOptions
  File "/data/delaunap/milabench/runs/code/lightning/utils.py", line 10, in <module>
    import pl_bolts.datamodules
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/pl_bolts/__init__.py", line 11, in <module>
    from pl_bolts import (  # noqa: E402
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/pl_bolts/callbacks/__init__.py", line 2, in <module>
    from pl_bolts.callbacks.byol_updates import BYOLMAWeightUpdate
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/pl_bolts/callbacks/byol_updates.py", line 4, in <module>
    from pytorch_lightning import Callback, LightningModule, Trainer
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 30, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/pytorch_lightning/callbacks/base.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/pytorch_lightning/utilities/apply_func.py", line 29, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/pytorch_lightning/utilities/imports.py", line 116, in <module>
    _TORCHTEXT_LEGACY: bool = _TORCHTEXT_AVAILABLE and _compare_version("torchtext", operator.lt, "0.11.0")
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/pytorch_lightning/utilities/imports.py", line 69, in _compare_version
    pkg = importlib.import_module(package)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/torchtext/__init__.py", line 6, in <module>
    from torchtext import _extension  # noqa: F401
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN3c1022getCustomClassTypeImplERKSt10type_index
```

Missing C++ symbol (`c10::getCustomClassTypeImpl(std::type_index const&)`).
libtorchtext does not seem to be using CUDA extensions.
This symbol is inside pytorch core C++ library!

**Comment by breuleux** [comment]
https://github.com/mila-iqia/milabench/blob/v2/benchmarks/pytorch-lightning/requirements.txt pins all of its dependencies, maybe unpinning them would help.

**Comment by Delaunay** [comment]
I dropped `--use-current-env` in the end.
The first resnest benchmark is running!

**Comment by Delaunay** [comment]
#23 fix the problem

**Comment by Delaunay** [comment]
```
milabench report
/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/data/delaunap/conda/envs/rocm/bin/milabench", line 8, in <module>
    sys.exit(main())
  File "/data/delaunap/milabench/milabench/cli.py", line 23, in main
    run_cli(Main)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/coleo/cli.py", line 602, in run_cli
    return call(opts=opts, args=args)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/coleo/cli.py", line 561, in thunk
    result = fn(*args)
  File "/data/delaunap/milabench/milabench/cli.py", line 276, in report
    summary,
UnboundLocalError: local variable 'summary' referenced before assignment
```

**Comment by Delaunay** [comment]
Summary of the issues/fix

* Fix AttributeError: 'TorchBenchmarkPack' object has no attribute 'constraints'
* Relax requirements to use `>=` instead of `==`
* Add the #23 fix for pytorch lightning 
* Fix backbone argument (no model were found)


Remains:

```
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/gym/core.py", line 241, in __getattr__
    return getattr(self.env, name)
soft_actor_critic.D0 >! 
  [Previous line repeated 1 more time]
soft_actor_critic.D0 >! 
AttributeError: 'PendulumEnv' object has no attribute 'seed'
```
and

```
ppo.0 >! 
  File "/data/delaunap/milabench/runs/code/sb3/utils/import_envs.py", line 2, in <module>
    import pybullet_envs  # pytype: disable=import-error
ppo.0 >! 
  File "/data/delaunap/milabench/runs/venv/sb3/lib/python3.9/site-packages/pybullet_envs/__init__.py", line 14, in <module>
    register(
ppo.0 >! 
  File "/data/delaunap/milabench/runs/venv/sb3/lib/python3.9/site-packages/pybullet_envs/__init__.py", line 6, in register
    if id in registry.env_specs:
ppo.0 >! 
AttributeError: 'dict' object has no attribute 'env_specs'
```
and
```
td3.D0 >! 
  File "/data/delaunap/milabench/runs/venv/sb3/lib/python3.9/site-packages/voir/overseer.py", line 55, in run
    func = find_script(script, field)
td3.D0 >! 
  File "/data/delaunap/milabench/runs/venv/sb3/lib/python3.9/site-packages/voir/overseer.py", line 90, in find_script
    exec(code, glb, glb)
td3.D0 >! 
  File "/data/delaunap/milabench/runs/code/sb3/train.py", line 15, in <module>
    import utils.import_envs  # noqa: F401 pytype: disable=import-error
td3.D0 >! 
  File "/data/delaunap/milabench/runs/code/sb3/utils/import_envs.py", line 2, in <module>
    import pybullet_envs  # pytype: disable=import-error
td3.D0 >! 
  File "/data/delaunap/milabench/runs/venv/sb3/lib/python3.9/site-packages/pybullet_envs/__init__.py", line 14, in <module>
    register(
td3.D0 >! 
  File "/data/delaunap/milabench/runs/venv/sb3/lib/python3.9/site-packages/pybullet_envs/__init__.py", line 6, in register
    if id in registry.env_specs:
td3.D0 >! 
AttributeError: 'dict' object has no attribute 'env_specs'
```

**Comment by Delaunay** [comment]
[out.txt](https://github.com/mila-iqia/milabench/files/9776934/out.txt)
