### ISSUE TITLE
Install crash with newest version of pytorch bench

### ISSUE THREAD

**Issue by Delaunay** [mila-iqia/milabench#29]
```
usage: install.py [-h] [--test-mode] [--continue_on_fail] [--verbose] [--component {distributed}] [models ...]
install.py: error: unrecognized arguments: --models
soft_actor_critic >! Command python install.py --models soft_actor_critic failed with exit code 2
Traceback (most recent call last):
  File "/data/delaunap/conda/envs/rocm/bin/milabench", line 8, in <module>
    sys.exit(main())
  File "/data/delaunap/milabench/milabench/cli.py", line 23, in main
    run_cli(Main)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/coleo/cli.py", line 602, in run_cli
    return call(opts=opts, args=args)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/coleo/cli.py", line 561, in thunk
    result = fn(*args)
  File "/data/delaunap/milabench/milabench/cli.py", line 224, in install
    mp.do_install(dash=simple_dash, force=force, sync=sync)
  File "/data/delaunap/milabench/milabench/multi.py", line 94, in do_install
    pack.checked_install(force=force, sync=sync)
  File "/data/delaunap/milabench/milabench/pack.py", line 99, in checked_install
    self.install()
  File "/data/delaunap/milabench/benchmarks/torchbench/benchfile.py", line 58, in install
    self.python("install.py", "--models", self.config["model"])
  File "/data/delaunap/milabench/milabench/pack.py", line 201, in python
    self.execute("python", *args, **kwargs)
  File "/data/delaunap/milabench/milabench/pack.py", line 188, in execute
    return self._nox_session.run(*args, **kwargs, external=True, silent=False)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/nox/sessions.py", line 287, in run
    return self._run(*args, env=env, **kwargs)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/nox/sessions.py", line 360, in _run
    return nox.command.run(args, env=env, paths=self.bin_paths, **kwargs)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/site-packages/nox/command.py", line 126, in run
    raise CommandFailed(f"Returned code {return_code}")
nox.command.CommandFailed: Returned code 2
```

**Comment by Delaunay** [comment]
After fixing `milabench/benchmarks/torchbench/benchfile.py`  by updating the install command I get a new error

```
Requirement already satisfied: numpy in ./runs/venv/torchbench/lib/python3.9/site-packages (from tensorboardX->-r /data/delaunap/milabench/runs/code/torchbench/requirements-soft_actor_critic.txt (line 1)) (1.23.4)
checking packages torch, torchvision, torchtext, torchaudio are installed...FAIL
Error: Users must first manually install packages ['torch', 'torchvision', 'torchtext', 'torchaudio'] before installing the benchmark.
```

**Comment by Delaunay** [comment]
After fixing by hacking the install script to install pytorch first

```
        torch = ["torch", "torchvision", "torchaudio"]
        for p in torch:
            self.pip_install(p, "--extra-index-url", "https://download.pytorch.org/whl/rocm5.2/")
 ```
 
 
 We get a numpy compatibility issue
 
 ```
soft_actor_critic.D0 > Traceback (most recent call last):
soft_actor_critic.D0 >   File "/data/delaunap/milabench/runs/venv/torchbench/bin/voir", line 8, in <module>
soft_actor_critic.D0 >     sys.exit(main())
soft_actor_critic.D0 >   File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/voir/cli.py", line 27, in main
soft_actor_critic.D0 >     instruments.extend(collect_contrib_instruments())
soft_actor_critic.D0 >   File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/voir/cli.py", line 13, in collect_contrib_instruments
soft_actor_critic.D0 >     results.append(entry_point.load())
soft_actor_critic.D0 >   File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2470, in load
soft_actor_critic.D0 >     self.require(*args, **kwargs)
soft_actor_critic.D0 >   File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2493, in require
soft_actor_critic.D0 >     items = working_set.resolve(reqs, env, installer, extras=self.extras)
soft_actor_critic.D0 >   File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/pkg_resources/__init__.py", line 800, in resolve
soft_actor_critic.D0 >     raise VersionConflict(dist, req).with_context(dependent_req)
soft_actor_critic.D0 > pkg_resources.VersionConflict: (numpy 1.21.2 (/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages), Requirement.parse('numpy<2.0.0,>=1.22.3'))
soft_actor_critic.D0 End (1): 2022-11-07 05:44:24.947305
[DONE] Reports directory: /data/delaunap/milabench/runs/runs/
```

This is because torchbench pin the numpy version to 1.21.2
by removing the numpy pin the bench can run

**Comment by Delaunay** [comment]
```
soft_actor_critic.D0 >! An error occurred

soft_actor_critic.D0 >! Traceback (most recent call last):
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/voir/phase.py", line 191, in _step_one
    next_phase = gen.send(ph.value)
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/voir/overseer.py", line 19, in __call__
    with self.probe:
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/giving/gvn.py", line 585, in __enter__
    self._enter()
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/ptera/probe.py", line 242, in _enter
    self._install_tooling()
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/ptera/probe.py", line 99, in _install_tooling
    autotool(selector)
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/ptera/overlay.py", line 403, in autotool
    verify(rval)
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/ptera/selector.py", line 868, in verify
    raise SelectorError(repr(display) + ": " + "\n".join(problems))
soft_actor_critic.D0 >! 
ptera.selector.SelectorError: sel("<function TorchVisionModel.train at 0x7f415f5cc4c0> as /0(real_input, !#endloop__ as step)"): Cannot find a variable named `real_input` in `<function TorchVisionModel.train at 0x7f415f5cc4c0>`
soft_actor_critic.D0 >! 
An error occurred

soft_actor_critic.D0 >! Traceback (most recent call last):
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/voir/phase.py", line 191, in _step_one
    next_phase = gen.send(ph.value)
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/voir/overseer.py", line 19, in __call__
    with self.probe:
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/giving/gvn.py", line 585, in __enter__
    self._enter()
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/ptera/probe.py", line 242, in _enter
    self._install_tooling()
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/ptera/probe.py", line 99, in _install_tooling
    autotool(selector)
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/ptera/overlay.py", line 403, in autotool
    verify(rval)
soft_actor_critic.D0 >! 
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/ptera/selector.py", line 868, in verify
    raise SelectorError(repr(display) + ": " + "\n".join(problems))
soft_actor_critic.D0 >! 
ptera.selector.SelectorError: sel("<function run_one_step at 0x7f415eb639d0> as /0(!cpu_dispatch_time)"): Cannot find a variable named `cpu_dispatch_time` in `<function run_one_step at 0x7f415eb639d0>`
soft_actor_critic.D0 >! 
/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
soft_actor_critic.D0 >! /data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
soft_actor_critic.D0 > Running train method from soft_actor_critic on cuda in eager mode with input batch size 256.
soft_actor_critic.D0 {'loss': 3.1270068675892193}
soft_actor_critic.D0 {'gpudata': {'0': {'memory': [0.0, 48685.0], 'load': 0.0, 'temperature': 22.0}}}
soft_actor_critic.D0 > batch_size: 256; step: True
soft_actor_critic.D0 {'loss': 4.1856551676121825}
soft_actor_critic.D0 > batch_size: 256; step: True
soft_actor_critic.D0 {'loss': 7.095333760201285}
soft_actor_critic.D0 > batch_size: 256; step: True
soft_actor_critic.D0 {'loss': 4.097200153060996}
soft_actor_critic.D0 > batch_size: 256; step: True
soft_actor_critic.D0 {'loss': 0.03265970918214597}
soft_actor_critic.D0 > batch_size: 256; step: True
soft_actor_critic.D0 {'loss': 4.183243615374786}
soft_actor_critic.D0 > batch_size: 256; step: True
soft_actor_critic.D0 {'loss': 2.3085968669784203}
soft_actor_critic.D0 > batch_size: 256; step: True
soft_actor_critic.D0 {'loss': 7.240552935781305}
soft_actor_critic.D0 > batch_size: 256; step: True
soft_actor_critic.D0 {'loss': 3.5324966804296563}
soft_actor_critic.D0 > batch_size: 256; step: True
soft_actor_critic.D0 {'loss': 2.889559053938694}
soft_actor_critic.D0 > batch_size: 256; step: True
soft_actor_critic.D0 {'loss': 0.002930343474809759}
soft_actor_critic.D0 > batch_size: 256; step: True
soft_actor_critic.D0 {'train_rate': 18774.54854727897}
soft_actor_critic.D0 {'loss': 4.027859970691497}
soft_actor_critic.D0 > batch_size: 256; step: True
soft_actor_critic.D0 {'train_rate': 17423.884170374007}
soft_actor_critic.D0 {'loss': 0.05373744639352114}
soft_actor_critic.D0 > batch_size: 256; step: True
soft_actor_critic.D0 {'train_rate': 21309.92615527894}
soft_actor_critic.D0 {'gpu_time': 13.579515933990479}
soft_actor_critic.D0 {'cpu_walltime': 13.617985000000001}
soft_actor_critic.D0 > GPU Time:             13.580 milliseconds
soft_actor_critic.D0 > CPU Total Wall Time:  13.618 milliseconds
soft_actor_critic.D0 End: 2022-11-07 05:47:03.594146
[DONE] Reports directory: /data/delaunap/milabench/runs/runs/mifodige.2022-11-07_05:46:45.787039
```

**Comment by Delaunay** [comment]
```
Traceback (most recent call last):
  File "/data/delaunap/milabench/runs/code/torchbench/install.py", line 90, in <module>
    versions = get_pkg_versions(TORCH_DEPS)
  File "/data/delaunap/milabench/runs/code/torchbench/utils/__init__.py", line 14, in get_pkg_versions
    module = importlib.import_module(module)
  File "/data/delaunap/conda/envs/rocm/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/torchtext/__init__.py", line 5, in <module>
    from . import vocab
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/torchtext/vocab/__init__.py", line 11, in <module>
    from .vocab_factory import (
  File "/data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/torchtext/vocab/vocab_factory.py", line 4, in <module>
    from torchtext._torchtext import (
ImportError: /data/delaunap/milabench/runs/venv/torchbench/lib/python3.9/site-packages/torchtext/_torchtext.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKSt10shared_ptrIS0_EPSo
```

Missing C++ symbol `c10::Type::isSubtypeOfExt(std::shared_ptr<c10::Type> const&, std::ostream*) const`

**Comment by Delaunay** [comment]
Fixed with newest version of pytorch
