### ISSUE TITLE
vjepa-single HPU

### ISSUE THREAD

**Issue by Delaunay** [mila-iqia/milabench#294]
Eager Mode
-------------

```
sudo apt-get install python3.10-full python-is-python3 virtualenv
git clone milabench
export MILABENCH_SOURCE=$(pwd)/milabench
export MILABENCH_HF_TOKEN=<TOKEN>

PT_HPU_LAZY_MODE=0 bash $MILABENCH_SOURCE/scripts/article/run_hpu.sh --select vjepa-single > out.out 2>&1
```

```
vjepa-single.D0 [stderr] Traceback (most recent call last):
vjepa-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/bin/voir", line 8, in <module>
vjepa-single.D0 [stderr]     sys.exit(main())
vjepa-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/voir/cli.py", line 128, in main
vjepa-single.D0 [stderr]     ov(sys.argv[1:] if argv is None else argv)
vjepa-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/voir/phase.py", line 331, in __call__
vjepa-single.D0 [stderr]     self._run(*args, **kwargs)
vjepa-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/voir/overseer.py", line 242, in _run
vjepa-single.D0 [stderr]     set_value(func())
vjepa-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/voir/scriptutils.py", line 37, in <lambda>
vjepa-single.D0 [stderr]     return lambda: exec(mainsection, glb, glb)
vjepa-single.D0 [stderr]   File "/homes/delaunap/milabench/benchmarks/vjepa/main.py", line 656, in <module>
vjepa-single.D0 [stderr]     main()
vjepa-single.D0 [stderr]   File "/homes/delaunap/milabench/benchmarks/vjepa/main.py", line 645, in main
vjepa-single.D0 [stderr]     _main(params)
vjepa-single.D0 [stderr]   File "/homes/delaunap/milabench/benchmarks/vjepa/main.py", line 509, in _main
vjepa-single.D0 [stderr]     (loss, loss_jepa, loss_reg, _new_lr, _new_wd, grad_stats, grad_stats_pred, optim_stats,), gpu_etime_ms = gpu_timer(train_step)
vjepa-single.D0 [stderr]   File "/homes/delaunap/milabench/benchmarks/vjepa/jepa/src/utils/logging.py", line 20, in gpu_timer
vjepa-single.D0 [stderr]     start = torch.cuda.Event(enable_timing=True)
vjepa-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/habana_frameworks/torch/gpu_migration/torch/cuda/streams.py", line 89, in __init__
vjepa-single.D0 [stderr]     super().__init__(enable_timing)
vjepa-single.D0 [stderr] TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

**Comment by Delaunay** [comment]
```
(torch) delaunap@vgaudi2-01:~/milabench/benchmarks/vjepa/jepa$ git diff
diff --git a/src/utils/logging.py b/src/utils/logging.py
index fcdd3fa..17f6c64 100644
--- a/src/utils/logging.py
+++ b/src/utils/logging.py
@@ -11,7 +11,7 @@ import sys
 import torch
 
 
-def gpu_timer(closure, log_timings=True):
+def gpu_timer(closure, log_timings=False):
     """ Helper to time gpu-time to execute closure() """
     log_timings = log_timings and torch.cuda.is_available()
```

```
PT_HPU_LAZY_MODE=0 bash $MILABENCH_SOURCE/scripts/article/run_hpu.sh --select vjepa-single > out.out 2>&1
```


```
```

**Comment by Delaunay** [comment]
```
PT_HPU_LAZY_MODE=0 bash $MILABENCH_SOURCE/scripts/article/run_hpu.sh --select vjepa-gpus > out.out 2>&1
```

```
System
------
cpu:      Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz
n_cpu:    160
product:  HL-225
n_gpu:    8
memory:   98304.0

Breakdown
---------
bench      | fail |   n | ngpu |       perf |   sem% |   std% | peak_memory |      score | weight
vjepa-gpus |    0 |   1 |    8 |      40.13 |   3.3% |  26.3% |       78016 |      40.13 |   1.00
```

**Comment by Delaunay** [comment]
LAZY MODE 
--------------

**Comment by Delaunay** [comment]
```
diff --git a/benchmarks/vjepa/main.py b/benchmarks/vjepa/main.py
index 18377b9..6e989ac 100644
--- a/benchmarks/vjepa/main.py
+++ b/benchmarks/vjepa/main.py
@@ -475,14 +475,19 @@ def _main(args, resume_preempt=False):

+                acc.mark_step()
                 if mixed_precision:
                     scaler.step(optimizer)
                     scaler.update()
                 else:
                     optimizer.step()
+                acc.mark_step()
```


```
vjepa-gpus.0 RuntimeError: synNodeCreateWithId failed for node: strided_insert with synStatus 1 [Invalid argument]. .
```

**Comment by Delaunay** [comment]
Note that process group is initialized [here](https://github.com/mila-iqia/milabench/blob/v1.0.0_RC1/benchmarks/vjepa/main.py#L641)
