### ISSUE TITLE
llm-lora-single on HPU

### ISSUE THREAD

**Issue by Delaunay** [mila-iqia/milabench#297]
Both Eager and Lazy produce the same error
```
PT_HPU_LAZY_MODE=1 bash $MILABENCH_SOURCE/scripts/article/run_hpu.sh --select llm-lora-single > out.out 2>&1
PT_HPU_LAZY_MODE=0 bash $MILABENCH_SOURCE/script
s/article/run_hpu.sh --select llm-lora-single > out.out 2>&1
```

```Traceback (most recent call last):
        |   File "/homes/delaunap/milabench/benchmarks/llm/recipes/lora_finetune_single_device.py", line 690, in <module>
        |     sys.exit(recipe_main())
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torchtune/config/_parse.py", line 50, in wrapper
        |     sys.exit(recipe_main(conf))
        |   File "/homes/delaunap/milabench/benchmarks/llm/recipes/lora_finetune_single_device.py", line 682, in recipe_main
        |     recipe.train()
        |   File "/homes/delaunap/milabench/benchmarks/llm/recipes/lora_finetune_single_device.py", line 574, in train
        |     logits = self._model(tokens, mask=mask, input_pos=input_pos)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1535, in _wrapped_call_impl
        |     return self._call_impl(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1544, in _call_impl
        |     return forward_call(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torchtune/modules/transformer.py", line 244, in forward
        |     h = layer(h, mask=mask, input_pos=input_pos)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1535, in _wrapped_call_impl
        |     return self._call_impl(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1544, in _call_impl
        |     return forward_call(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py", line 168, in forward
        |     return self.checkpoint_fn(  # type: ignore[misc]
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
        |     return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
        |     return fn(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 36, in inner
        |     return fn(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 493, in checkpoint
        |     next(gen)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1387, in _checkpoint_without_reentrant_generator
        |     fwd_devices, fwd_device_states = get_device_states(*args)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 180, in get_device_states
        |     with device_module.device(device_id):
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/habana_frameworks/torch/hpu/__init__.py", line 349, in __init__
        |     env_device_idx = _get_device_id_from_module_id(_get_module_id_from_environ())
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/habana_frameworks/torch/hpu/_utils.py", line 71, in _get_device_id_from_module_id
        |     if available_modules[index] == module_id:
        | IndexError: list index out of range
        | 
```

**Comment by Delaunay** [comment]
I was able to make llm-lora-single run.There is a bug inside `/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/habana_frameworks/torch/hpu/_utils.py`

`hpu.device_count()` returns 8 when only one device was made available.

```
    for index in range(hpu.device_count()) : 
        if available_modules[index] == module_id:
            return index
    return 0
```
fixed code:

```
    for index in range(len(available_modules)): 
        if available_modules[index] == module_id:
            return index
```
