### ISSUE TITLE
llm-full-mp-gpus on HPU

### ISSUE THREAD

**Issue by Delaunay** [mila-iqia/milabench#299]
```
llm-full-mp-gpus.0 [stderr] [rank0]: Traceback (most recent call last):
llm-full-mp-gpus.0 [stderr] [rank0]:   File "/homes/delaunap/milabench/benchmarks/llm/recipes/full_finetune_distributed.py", line 645, in <module>
llm-full-mp-gpus.0 [stderr] [rank0]:     sys.exit(recipe_main())
llm-full-mp-gpus.0 [stderr] [rank0]:   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torchtune/config/_parse.py", line 50, in wrapper
llm-full-mp-gpus.0 [stderr] [rank0]:     sys.exit(recipe_main(conf))
llm-full-mp-gpus.0 [stderr] [rank0]:   File "/homes/delaunap/milabench/benchmarks/llm/recipes/full_finetune_distributed.py", line 632, in recipe_main
llm-full-mp-gpus.0 [stderr] [rank0]:     recipe = FullFinetuneRecipeDistributed(cfg=cfg)
llm-full-mp-gpus.0 [stderr] [rank0]:   File "/homes/delaunap/milabench/benchmarks/llm/recipes/full_finetune_distributed.py", line 116, in __init__
llm-full-mp-gpus.0 [stderr] [rank0]:     raise RuntimeError(
llm-full-mp-gpus.0 [stderr] [rank0]: RuntimeError: Using fused optimizer on CPU is only supported in PyTorch nightly.
```

**Comment by Delaunay** [comment]
```
--- a/benchmarks/llm/configs/llama3_70B_full.yaml
+++ b/benchmarks/llm/configs/llama3_70B_full.yaml
@@ -94,9 +94,9 @@ gradient_accumulation_steps: 1
 device: cuda
 
 # Memory management
-enable_activation_checkpointing: True
-memory_efficient_fsdp_wrap: True
-fsdp_cpu_offload: True
+enable_activation_checkpointing: false
+memory_efficient_fsdp_wrap: false
+fsdp_cpu_offload: false
 
 # Reduced precision
 dtype: bf16
```

**Comment by Delaunay** [comment]
Dies after running 15/30 (50% of the bench)


```

llm-full-mp-gpus.0 [data] {'cpudata': {'load': 6.8, 'memory': [217340166144, 1081801142272]}, 'task': 'main', 'time':
1729186143.3196068}
llm-full-mp-gpus.0 [stderr] Synapse detected a device critical error that requires a restart. Killing process in 5 seconds
(hl: 4) 10:28:55 [No progress error]
llm-full-mp-gpus.0 [stderr] W1017 10:29:15.898000 140525722707968 torch/distributed/elastic/multiprocessing/api.py:851]
Sending process 3687945 closing signal SIGTERM
llm-full-mp-gpus.0 [stderr] W1017 10:29:15.899000 140525722707968 torch/distributed/elastic/multiprocessing/api.py:851]
Sending process 3687946 closing signal SIGTERM
llm-full-mp-gpus.0 [stderr] W1017 10:29:15.899000 140525722707968 torch/distributed/elastic/multiprocessing/api.py:851]
Sending process 3687947 closing signal SIGTERM
llm-full-mp-gpus.0 [stderr] W1017 10:29:15.899000 140525722707968 torch/distributed/elastic/multiprocessing/api.py:851]
Sending process 3687948 closing signal SIGTERM
llm-full-mp-gpus.0 [stderr] W1017 10:29:15.899000 140525722707968 torch/distributed/elastic/multiprocessing/api.py:851]
Sending process 3687949 closing signal SIGTERM
llm-full-mp-gpus.0 [stderr] W1017 10:29:15.899000 140525722707968 torch/distributed/elastic/multiprocessing/api.py:851]
Sending process 3687951 closing signal SIGTERM
llm-full-mp-gpus.0 [stderr] W1017 10:29:15.899000 140525722707968 torch/distributed/elastic/multiprocessing/api.py:851]
Sending process 3687952 closing signal SIGTERM
llm-full-mp-gpus.0 [stderr] W1017 10:29:45.899000 140525722707968 torch/distributed/elastic/multiprocessing/api.py:868] Unable to
shutdown process 3687948 via Signals.SIGTERM, forcefully exiting via Signals.SIGKILL

```
