### ISSUE TITLE
[HPU] rlhf

### ISSUE THREAD

**Issue by Delaunay** [mila-iqia/milabench#303]
Lazy Mode
------------

`habana_frameworks/torch/gpu_migration/torch/cuda/random.py`

Changed
```
          	pyhlml.hlmlInit()
                count = pyhlml.hlmlDeviceGetCount()
          	pyhlml.hlmlShutdown()
```
to
```
        	try:
            	   pyhlml.hlmlInit()
            	   count = pyhlml.hlmlDeviceGetCount()
            	   pyhlml.hlmlShutdown()
        	except Exception:
            	  count = pyhlml.hlmlDeviceGetCount()
```

Latest error
```
rlhf-single.D5
==============
  * no training rate retrieved
  * Error codes = 1
  * 1 exceptions found
  0%|          | 0/254 [00:02<?, ?it/s]
        | Traceback (most recent call last):
        |   File "/homes/delaunap/milabench/benchmarks/rlhf/main.py", line 137, in <module>
        |     main()
        |   File "/homes/delaunap/milabench/benchmarks/rlhf/main.py", line 128, in main
        |     trainer.train()
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/trl/trainer/ppov2_trainer.py", line 309, in train
        |     query_responses, logitss = batch_generation(
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        |     return func(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/trl/trainer/utils.py", line 1176, in batch_generation
        |     query_response, logits = generate(
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/trl/trainer/utils.py", line 1151, in generate
        |     output = lm_backbone.generate(
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        |     return func(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/generation/utils.py", line 2024, in generate
        |     result = self._sample(
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/generation/utils.py", line 3038, in _sample
        |     unfinished_sequences = unfinished_sequences & ~stopping_criteria(input_ids, scores)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/generation/stopping_criteria.py", line 509, in __call__
        |     is_done = torch.full((input_ids.shape[0],), False, device=input_ids.device, dtype=torch.bool)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/habana_frameworks/torch/gpu_migration/torch/_C/_VariableFunctions.py", line 244, in full
        |     return TorchModuleRegister.full(*args, **kwargs)
        | RuntimeError: [Rank:0] FATAL ERROR :: MODULE:PT_BRIDGE Exception in acc thread pool task has been thrown: Got a non-HPU tensor, expecting an HPU tensor
        | [Rank:0] Habana exception raised from GetHbLazyTensor at aten_lazy_bridge.cpp:290
```

**Comment by Delaunay** [comment]
Changed voir so

```
@contextmanager
def hlmlinit():
    try:
        pyhlml.hlmlInit()
        yield
        pyhlml.hlmlShutdown()
    except pyhlml.hlml_error.HLMLError_AlreadyInitialized:
        pass
 
...


        with hlmlinit():
            deviceCount = pyhlml.hlmlDeviceGetCount()
            for i in range(0, deviceCount):
                self.handles[i] = pyhlml.hlmlDeviceGetHandleByIndex(i)

...


    def get_gpus_info(self, selection=None):
        with hlmlinit():
            return make_gpu_infos(self.handles, selection)
```

**Comment by Delaunay** [comment]
Eager Mode
-------------


```
        | Traceback (most recent call last):
        |   File "/homes/delaunap/milabench/benchmarks/rlhf/main.py", line 137, in <module>
        |     main()
        |   File "/homes/delaunap/milabench/benchmarks/rlhf/main.py", line 128, in main
        |     trainer.train()
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/trl/trainer/ppov2_trainer.py", line 309, in train
        |     query_responses, logitss = batch_generation(
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        |     return func(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/trl/trainer/utils.py", line 1176, in batch_generation
        |     query_response, logits = generate(
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/trl/trainer/utils.py", line 1151, in generate
        |     output = lm_backbone.generate(
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        |     return func(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/generation/utils.py", line 2024, in generate
        |     result = self._sample(
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/generation/utils.py", line 2982, in _sample
        |     outputs = self(**model_inputs, return_dict=True)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1535, in _wrapped_call_impl
        |     return self._call_impl(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1544, in _call_impl
        |     return forward_call(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 989, in forward
        |     outputs = self.gpt_neox(
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1535, in _wrapped_call_impl
        |     return self._call_impl(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1544, in _call_impl
        |     return forward_call(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 880, in forward
        |     outputs = layer(
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1535, in _wrapped_call_impl
        |     return self._call_impl(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1544, in _call_impl
        |     return forward_call(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 648, in forward
        |     self.input_layernorm(hidden_states),
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1535, in _wrapped_call_impl
        |     return self._call_impl(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1544, in _call_impl
        |     return forward_call(*args, **kwargs)
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 201, in forward
        |     return F.layer_norm(
        |   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/functional.py", line 2573, in layer_norm
        |     return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
        | RuntimeError: Expected all tensors to be on the HPU device, but found at least one input[idx=2] on cpu (details: torch.FloatTensor)
```

**Comment by Delaunay** [comment]
Device placement is wrong, even after replacing `Accelerator` by the Gaudi version

```
        import torchcompat.core as comp
        accelerator = comp.accelerate.Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps)
        print(accelerator)
```

```
rlhf-single.D0 [stdout] <optimum.habana.accelerate.accelerator.GaudiAccelerator object at 0x7efc4cb46c50>
rlhf-single.D0 [stdout] DEVICE: cpu
```

**Comment by Delaunay** [comment]
After forcing device to be hpu, still does not work

```
rlhf-single.D0 [stderr]   warnings.warn(
rlhf-single.D0 [stderr] Traceback (most recent call last):
rlhf-single.D0 [stderr]   File "/homes/delaunap/milabench/benchmarks/rlhf/main.py", line 137, in <module>
rlhf-single.D0 [stderr]     main()
rlhf-single.D0 [stderr]   File "/homes/delaunap/milabench/benchmarks/rlhf/main.py", line 128, in main
rlhf-single.D0 [stderr]     trainer.train()
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/trl/trainer/ppov2_trainer.py", line 316, in train
rlhf-single.D0 [stderr]     query_responses, logitss = batch_generation(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in 
decorate_context
rlhf-single.D0 [stderr]     return func(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/trl/trainer/utils.py", line 1178, in 
batch_generation
rlhf-single.D0 [stderr]     query_response, logits = generate(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/trl/trainer/utils.py", line 1153, in generate
rlhf-single.D0 [stderr]     output = lm_backbone.generate(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in 
decorate_context
rlhf-single.D0 [stderr]     return func(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/generation/utils.py", line 1989, in 
generate
rlhf-single.D0 [stderr]     result = self._sample(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/generation/utils.py", line 2932, in 
_sample
rlhf-single.D0 [stderr]     outputs = self(**model_inputs, return_dict=True)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1535, in 
_wrapped_call_impl
rlhf-single.D0 [stderr]     return self._call_impl(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1544, in 
_call_impl
rlhf-single.D0 [stderr]     return forward_call(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", 
line 989, in forward
rlhf-single.D0 [stderr]     outputs = self.gpt_neox(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1535, in 
_wrapped_call_impl
rlhf-single.D0 [stderr]     return self._call_impl(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1544, in 
_call_impl
rlhf-single.D0 [stderr]     return forward_call(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", 
line 824, in forward
rlhf-single.D0 [stderr]     inputs_embeds = self.embed_in(input_ids)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1535, in 
_wrapped_call_impl
rlhf-single.D0 [stderr]     return self._call_impl(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1544, in 
_call_impl
rlhf-single.D0 [stderr]     return forward_call(*args, **kwargs)
rlhf-single.D0 [stderr]   File 
"/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/habana_frameworks/torch/gpu_migration/torch/nn/modules/sparse.py", line 45, in 
forward
rlhf-single.D0 [stderr]     output = F.embedding(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/functional.py", line 2264, in embedding
rlhf-single.D0 [stderr]     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
rlhf-single.D0 [stderr] RuntimeError: Expected all tensors to be on the HPU device, but found at least one input[idx=0] on cpu (details: 
torch.FloatTensor)
```

**Comment by Delaunay** [comment]
Custom accelerate that overrides the device

```
import torchcompat.core as comp

class AcceleratorCustom(comp.accelerate.Accelerator):
    @property
    def device(self):
        return comp.fetch_device()
```


```
rlhf-single.D0 [stderr] Traceback (most recent call last):
rlhf-single.D0 [stderr]   File "/homes/delaunap/milabench/benchmarks/rlhf/main.py", line 137, in <module>
rlhf-single.D0 [stderr]     main()
rlhf-single.D0 [stderr]   File "/homes/delaunap/milabench/benchmarks/rlhf/main.py", line 128, in main
rlhf-single.D0 [stderr]     trainer.train()
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/trl/trainer/ppov2_trainer.py", line 323, in train
rlhf-single.D0 [stderr]     query_responses, logitss = batch_generation(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in 
decorate_context
rlhf-single.D0 [stderr]     return func(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/trl/trainer/utils.py", line 1178, in 
batch_generation
rlhf-single.D0 [stderr]     query_response, logits = generate(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/trl/trainer/utils.py", line 1153, in generate
rlhf-single.D0 [stderr]     output = lm_backbone.generate(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in 
decorate_context
rlhf-single.D0 [stderr]     return func(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/generation/utils.py", line 1989, in 
generate
rlhf-single.D0 [stderr]     result = self._sample(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/generation/utils.py", line 2932, in 
_sample
rlhf-single.D0 [stderr]     outputs = self(**model_inputs, return_dict=True)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1535, in 
_wrapped_call_impl
rlhf-single.D0 [stderr]     return self._call_impl(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1544, in 
_call_impl
rlhf-single.D0 [stderr]     return forward_call(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", 
line 989, in forward
rlhf-single.D0 [stderr]     outputs = self.gpt_neox(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1535, in 
_wrapped_call_impl
rlhf-single.D0 [stderr]     return self._call_impl(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1544, in 
_call_impl
rlhf-single.D0 [stderr]     return forward_call(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", 
line 880, in forward
rlhf-single.D0 [stderr]     outputs = layer(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1535, in 
_wrapped_call_impl
rlhf-single.D0 [stderr]     return self._call_impl(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1544, in 
_call_impl
rlhf-single.D0 [stderr]     return forward_call(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", 
line 647, in forward
rlhf-single.D0 [stderr]     attention_layer_outputs = self.attention(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1535, in 
_wrapped_call_impl
rlhf-single.D0 [stderr]     return self._call_impl(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1544, in 
_call_impl
rlhf-single.D0 [stderr]     return forward_call(*args, **kwargs)
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", 
line 439, in forward
rlhf-single.D0 [stderr]     query, key, value, present = self._attn_projections_and_rope(
rlhf-single.D0 [stderr]   File "/homes/delaunap/hpu/results/venv/torch/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", 
line 222, in _attn_projections_and_rope
rlhf-single.D0 [stderr]     query_pass = query[..., self.rotary_ndims :]
rlhf-single.D0 [stderr] RuntimeError: Graph compile failed. synStatus=synStatus 26 [Generic failure].
  0%|          | 0/254 [00:00<?, ?it/s]
rlhf-single.D0 [end (1)] /homes/delaunap/milabench/benchmarks/rlhf/main.py --output_dir /homes/delaunap/hpu/results/extra/rlhf-single/output 
--model_name_or_path EleutherAI/pythia-1b-deduped --per_device_train_batch_size 64 --logging_strategy no --log_level critical --bf16 [at 2024-10-15 
```
