### ISSUE TITLE
milabench install requires GPU

### ISSUE THREAD

**Issue by Delaunay** [mila-iqia/milabench#42]
This is problematic if we want to pre-install benchmark inside a container.
The container builder might not have access to a GPU

```
sudo docker run -it --rm -v /opt/results/:/milabench/results -v /opt/runs:/milabench/runs milabench milabench install
Traceback (most recent call last):
  File "/opt/anaconda/bin/milabench", line 8, in <module>
    sys.exit(main())
  File "/milabench/milabench/milabench/cli.py", line 23, in main
    run_cli(Main)
  File "/opt/anaconda/lib/python3.10/site-packages/coleo/cli.py", line 628, in run_cli
    return call(opts=opts, args=args)
  File "/opt/anaconda/lib/python3.10/site-packages/coleo/cli.py", line 587, in thunk
    result = fn(*args)
  File "/milabench/milabench/milabench/cli.py", line 222, in install
    mp = _get_multipack(dev=dev)
  File "/milabench/milabench/milabench/cli.py", line 137, in _get_multipack
    objects[name] = get_pack(defn)
  File "/milabench/milabench/milabench/cli.py", line 55, in get_pack
    pack_glb = runpy.run_path(str(pack / "benchfile.py"))
  File "/opt/anaconda/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/anaconda/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/anaconda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/milabench/milabench/benchmarks/pytorch-lightning/benchfile.py", line 8, in <module>
    class PLBenchmark(Package):
  File "/milabench/milabench/benchmarks/pytorch-lightning/benchfile.py", line 15, in PLBenchmark
    raise ValueError(f"Unsupported arch: {gpu.arch}")
ValueError: Unsupported arch: cpu
```

**Comment by breuleux** [comment]
It has to do with auto-detection of the architecture, set the environment variable `MILABENCH_GPU_ARCH=cuda` or `MILABENCH_GPU_ARCH=rocm` and it should use the appropriate requirements.

**Comment by Delaunay** [comment]
are we going for 1 container => 1 vendor approach ?

**Comment by breuleux** [comment]
Yeah, I think that will be much simpler.
