### ISSUE TITLE
[low] ptera.selfless.ConflictError: Multiple values with same priority conflict for variable 'base'

### ISSUE THREAD

**Issue by lebrice** [mila-iqia/milabench#9]
## Bug

Somewhat Minor bug: After creating a new project from the _template using:
```console
cp-template benchmarks/_template benchmarks/pytorch-lightning
```
If I first incorrectly use the `milabench prepare` command, without passing the `--base` argument, then from that point onward, passing a value for `--base` doesn't work anymore:

```console
(milabench) normandf@kepler5:~/milabench$ milabench prepare benchmarks/pytorch-lightning/dev.yaml
Error: Neither --base nor $MILABENCH_BASE are set.
(milabench) normandf@kepler5:~/milabench$ milabench prepare benchmarks/pytorch-lightning/dev.yaml --base $SCRATCH
Traceback (most recent call last):
  File "/home/mila/n/normandf/.conda/envs/milabench/bin/milabench", line 8, in <module>
    sys.exit(main())
  File "/home/mila/n/normandf/milabench/milabench/cli.py", line 16, in main
    run_cli(Main)
  File "/home/mila/n/normandf/.conda/envs/milabench/lib/python3.9/site-packages/coleo/cli.py", line 585, in run_cli
    return call(opts=opts, args=args)
  File "/home/mila/n/normandf/.conda/envs/milabench/lib/python3.9/site-packages/coleo/cli.py", line 544, in thunk
    result = fn(*args)
  File "/home/mila/n/normandf/.conda/envs/milabench/lib/python3.9/site-packages/ptera/core.py", line 868, in __call__
    rval = super().__call__(*self.partial_args, *args, **kwargs)
  File "/home/mila/n/normandf/.conda/envs/milabench/lib/python3.9/site-packages/ptera/selfless.py", line 679, in __call__
    return self.fn(self, *args, **kwargs)
  File "/home/mila/n/normandf/milabench/milabench/cli.py", line 133, in prepare
    mp = _get_multipack(dev=dev)
  File "/home/mila/n/normandf/.conda/envs/milabench/lib/python3.9/site-packages/ptera/core.py", line 868, in __call__
    rval = super().__call__(*self.partial_args, *args, **kwargs)
  File "/home/mila/n/normandf/.conda/envs/milabench/lib/python3.9/site-packages/ptera/selfless.py", line 679, in __call__
    return self.fn(self, *args, **kwargs)
  File "/home/mila/n/normandf/milabench/milabench/cli.py", line 37, in _get_multipack
    base: Option & str = None
  File "/home/mila/n/normandf/.conda/envs/milabench/lib/python3.9/site-packages/ptera/core.py", line 479, in interact
    value = choose([value, fr_value, from_state], name=sym)
  File "/home/mila/n/normandf/.conda/envs/milabench/lib/python3.9/site-packages/ptera/selfless.py", line 707, in choose
    raise ConflictError(
ptera.selfless.ConflictError: Multiple values with same priority conflict for variable 'base': None, /network/scratch/n/normandf
```

I'm guessing it's probably setting a value of `None` into the environment variables or something, from the first call?

## Temporary solution

I've set the environment variable, so I don't need to pass the `--base` value:
```console
(milabench) normandf@kepler5:~/milabench$ export MILABENCH_BASE=$SCRATCH
(milabench) normandf@kepler5:~/milabench$ milabench prepare benchmarks/pytorch-lightning/dev.yaml
(milabench) normandf@kepler5:~/milabench$ # (no problem)
```

**Comment by breuleux** [comment]
You seem to be using an old version of `ptera` (pre 1.0), possibly from installing `milatools` before.

**Comment by breuleux** [comment]
You might also need to `pip install -U coleo` as well. I'm not sure why the `pip install -e` did not upgrade the versions...

**Comment by lebrice** [comment]
Indeed! Upgrading `ptera` and `coleo` solved this issue. Closing this.
